#!/usr/bin/env nu
const CORE = path self ./modules/core.nu
use $CORE [nu-home machine-context]
const SUBPROCESS = path self ./modules/subprocess.nu
use $SUBPROCESS [run-command command-failure-message]

# ============================================================
# Ensure canonical config.nu imports the management module.
# ============================================================

def main [] {
    let context = (machine-context)
    let data_root = ($context.data_root | path expand)

    let config_file = (
        (nu-home)
        | path join ".config" "nushell" "config.nu"
    )

    let module_file = (
        (nu-home)
        | path join ".config" "nushell" "modules" "dotfiles.nu"
    )

    if not ($module_file | path exists) {
        error make {
            msg: $"Managed module not found: ($module_file)"
        }
    }

    if not ($config_file | path exists) {
        mkdir ($config_file | path dirname)
        "" | save $config_file
    }

    # config.nu is synchronized and sources platform.nu; guarantee the file
    # exists on every OS (empty no-op is fine) so a config synced from another
    # OS cannot make Nushell fail to start.
    let platform_file = ((nu-home) | path join ".config" "dotfiles" "platform.nu")
    if not ($platform_file | path exists) {
        mkdir ($platform_file | path dirname)
        "# Generated by Initial-setup. Machine-local; may be empty on some OSes." | save --force $platform_file
    }
    let import_line = "use ~/.config/nushell/modules/dotfiles.nu *"
    let platform_line = "source-env ~/.config/dotfiles/platform.nu"
    let local_line = "source ~/.config/dotfiles/local.nu"
    mut current = (open --raw $config_file)

    if not ($current | str contains $import_line) {
        let separator = (
            if ($current | str trim | is-empty) {
                ""
            } else {
                char nl
            }
        )

        $current = (
            $current + $separator + "# Dotfiles management" + (char nl) + $import_line + (char nl)
        )
    }

    if not ($current | str contains $platform_line) {
        let separator = (
            if ($current | str trim | is-empty) {
                ""
            } else {
                char nl
            }
        )

        $current = (
            $current + $separator + "# Machine-local PATH bridge" + (char nl) + $platform_line + (char nl)
        )
    }

    if not ($current | str contains $local_line) {
        let separator = (
            if ($current | str trim | is-empty) {
                ""
            } else {
                char nl
            }
        )

        $current = (
            $current + $separator + "# Machine-local setup (not synchronized)" + (char nl) + $local_line + (char nl)
        )
    }

    $current | save --force $config_file
    print $"[update] ($config_file)"

    let args = [
        "--source"
        ($data_root | into string)
        "add"
        "--secrets"
        "error"
        ($config_file | into string)
    ]

    let result = (run-command "chezmoi" $args --live)
    if not $result.ok {
        error make { msg: (command-failure-message "Update Nushell config in private source" $result) }
    }
}
