#!/usr/bin/env nu

# ============================================================
# Bridge platform-native Nushell/Neovim paths to canonical
# ~/.config paths.
# ============================================================

def nu-home [] {
    let test_mode = ($env.INITIAL_SETUP_TEST_MODE? | default "" | str trim)
    let override = ($env.INITIAL_SETUP_HOME_OVERRIDE? | default "" | str trim)

    if $test_mode == "1" and not ($override | is-empty) {
        return ($override | path expand)
    }

    let home_path = ($nu | get --optional home-path)

    if $home_path != null {
        return $home_path
    }

    let home_dir = ($nu | get --optional home-dir)

    if $home_dir != null {
        return $home_dir
    }

    error make {
        msg: "Unable to determine the Nushell home directory."
    }
}

def backup-file [file: path] {
    let p = ($file | path expand)

    if not ($p | path exists) {
        return
    }

    let backup = $"($p).pre-dotfiles"

    if not ($backup | path exists) {
        cp $p $backup
        print $"[backup] ($p) -> ($backup)"
    }
}


def write-posix-wrapper [name: string fallback: string] {
    if not ($nu.os-info.name in ["linux" "macos"]) {
        return
    }

    if not (which $name | is-empty) {
        return
    }

    let candidates = (which $fallback)
    if ($candidates | is-empty) {
        return
    }

    let target = ($candidates | get 0.path | path expand)
    let bin_dir = ((nu-home) | path join ".local" "bin")
    let wrapper = ($bin_dir | path join $name)
    mkdir $bin_dir

    if ($wrapper | path exists) and (($wrapper | path type) != "file") {
        print ("[warn] Cannot create command shim because path is occupied: " + ($wrapper | into string))
        return
    }

    if ($wrapper | path exists) {
        let current = (open --raw $wrapper)
        if not ($current | str contains "Generated by Initial-setup") {
            print ("[warn] Existing user command was not overwritten: " + ($wrapper | into string))
            return
        }
    }

    let target_literal = (($target | into string) | str replace --all '"' '\\"')
    [
        "#!/bin/sh"
        "# Generated by Initial-setup"
        ('exec "' + $target_literal + '" "$@"')
        ""
    ]
    | str join (char nl)
    | save --force $wrapper

    if not (which chmod | is-empty) {
        ^chmod 0755 $wrapper
        if ($env.LAST_EXIT_CODE | default 0) != 0 {
            print ("[warn] Could not mark command shim executable: " + ($wrapper | into string))
            return
        }
    }

    print ("[ok] Command shim: " + $name + " -> " + ($target | into string))
}

def write-platform-env [] {
    if not ($nu.os-info.name in ["linux" "macos"]) {
        return
    }

    let home = (nu-home)
    let file = ($home | path join ".config" "dotfiles" "platform.nu")
    mkdir ($file | path dirname)

    let candidates = [
        ($home | path join ".local" "bin")
        ($home | path join ".cargo" "bin")
        ($home | path join ".juliaup" "bin")
    ]

    let literals = (
        $candidates
        | each { |item| "    " + (($item | into string) | to nuon) }
        | str join (char nl)
    )

    let content = (
        "# Generated by Initial-setup. Machine-local and not synchronized." + (char nl)
        + "let initial_setup_user_bins = [" + (char nl)
        + $literals + (char nl)
        + "]" + (char nl)
        + "$env.PATH = (" + (char nl)
        + "    $initial_setup_user_bins" + (char nl)
        + "    | where { |item| $item | path exists }" + (char nl)
        + "    | append $env.PATH" + (char nl)
        + "    | uniq" + (char nl)
        + ")" + (char nl)
    )

    $content | save --force $file
    print ("[ok] Machine-local PATH bridge: " + ($file | into string))
}

def main [] {
    let canonical_root = (
        (nu-home)
        | path join ".config"
    )

    let canonical_nvim = (
        $canonical_root
        | path join "nvim"
    )

    let canonical_nushell = (
        $canonical_root
        | path join "nushell"
    )

    let native_nu_dir = (
        $nu.default-config-dir
        | path expand
    )

    if $native_nu_dir != $canonical_nushell {
        mkdir $native_nu_dir

        let native_config = ($native_nu_dir | path join "config.nu")
        let native_env = ($native_nu_dir | path join "env.nu")
        let canonical_config = ($canonical_nushell | path join "config.nu")
        let canonical_env = ($canonical_nushell | path join "env.nu")

        backup-file $native_config
        backup-file $native_env

        let config_literal = ($canonical_config | to nuon)
        let env_literal = ($canonical_env | to nuon)

        (
            "# Generated by Initial-setup" + (char nl) + $"source ($config_literal)" + (char nl)
        )
        | save --force $native_config

        (
            "# Generated by Initial-setup" + (char nl) + $"source-env ($env_literal)" + (char nl)
        )
        | save --force $native_env

        print "[ok] Nushell platform shim installed"
    } else {
        print "[ok] Nushell already uses canonical path"
    }

    if not (which nvim | is-empty) {
        let nvim_args = [
            "--headless"
            "-u"
            "NONE"
            "-c"
            "lua io.write(vim.fn.stdpath('config'))"
            "-c"
            "qa"
        ]

        let native_nvim = (
            ^nvim ...$nvim_args
            | str trim
            | path expand
        )

        if $native_nvim != $canonical_nvim {
            mkdir $native_nvim

            let native_init = (
                $native_nvim
                | path join "init.lua"
            )

            backup-file $native_init

            let lua_path = (
                $canonical_nvim
                | str replace --all '\' '/'
            )

            (
                "-- Generated by Initial-setup" + (char nl) + $"local canonical = \"($lua_path)\"" + (char nl) + "vim.opt.runtimepath:prepend(canonical)" + (char nl) + "dofile(canonical .. \"/init.lua\")" + (char nl)
            )
            | save --force $native_init

            print "[ok] Neovim platform shim installed"
        } else {
            print "[ok] Neovim already uses canonical path"
        }
    }

    write-posix-wrapper "fd" "fdfind"
    write-posix-wrapper "bat" "batcat"
    write-platform-env

}
