#!/usr/bin/env nu

# ============================================================
# Bridge platform-native Nushell/Neovim paths to canonical
# ~/.config paths.
# ============================================================

def nu-home [] {
    let home_path = ($nu | get --optional home-path)

    if $home_path != null {
        return $home_path
    }

    let home_dir = ($nu | get --optional home-dir)

    if $home_dir != null {
        return $home_dir
    }

    error make {
        msg: "Unable to determine the Nushell home directory."
    }
}

def backup-file [file: path] {
    let p = ($file | path expand)

    if not ($p | path exists) {
        return
    }

    let backup = $"($p).pre-dotfiles"

    if not ($backup | path exists) {
        cp $p $backup
        print $"[backup] ($p) -> ($backup)"
    }
}

def main [] {
    let canonical_root = (
        (nu-home)
        | path join ".config"
    )

    let canonical_nvim = (
        $canonical_root
        | path join "nvim"
    )

    let canonical_nushell = (
        $canonical_root
        | path join "nushell"
    )

    let native_nu_dir = (
        $nu.default-config-dir
        | path expand
    )

    if $native_nu_dir != $canonical_nushell {
        mkdir $native_nu_dir

        let native_config = ($native_nu_dir | path join "config.nu")
        let native_env = ($native_nu_dir | path join "env.nu")
        let canonical_config = ($canonical_nushell | path join "config.nu")
        let canonical_env = ($canonical_nushell | path join "env.nu")

        backup-file $native_config
        backup-file $native_env

        let config_literal = ($canonical_config | to nuon)
        let env_literal = ($canonical_env | to nuon)

        (
            "# Generated by Initial-setup" + (char nl) + $"source ($config_literal)" + (char nl)
        )
        | save --force $native_config

        (
            "# Generated by Initial-setup" + (char nl) + $"source-env ($env_literal)" + (char nl)
        )
        | save --force $native_env

        print "[ok] Nushell platform shim installed"
    } else {
        print "[ok] Nushell already uses canonical path"
    }

    if not (which nvim | is-empty) {
        let nvim_args = [
            "--headless"
            "-u"
            "NONE"
            "-c"
            "lua io.write(vim.fn.stdpath('config'))"
            "-c"
            "qa"
        ]

        let native_nvim = (
            ^nvim ...$nvim_args
            | str trim
            | path expand
        )

        if $native_nvim != $canonical_nvim {
            mkdir $native_nvim

            let native_init = (
                $native_nvim
                | path join "init.lua"
            )

            backup-file $native_init

            let lua_path = (
                $canonical_nvim
                | str replace --all '\' '/'
            )

            (
                "-- Generated by Initial-setup" + (char nl) + $"local canonical = \"($lua_path)\"" + (char nl) + "vim.opt.runtimepath:prepend(canonical)" + (char nl) + "dofile(canonical .. \"/init.lua\")" + (char nl)
            )
            | save --force $native_init

            print "[ok] Neovim platform shim installed"
        } else {
            print "[ok] Neovim already uses canonical path"
        }
    }
}
