# Command runtime: the generated installed command shim.
#
# Since the shim layout, the user's Nushell module directory receives only a
# small generated `dotfiles.nu` shim. Each command forwards to the checkout
# recorded as `tools_root` (scripts/dotcmd.nu), so script and module updates in
# the checkout take effect without re-running setup. Only a changed command
# list/signature needs `refresh-commands.nu`; the runner warns when that is so.
# Generating the shim loads the checkout's `dotfiles.nu` in a child process,
# so a checkout with missing/broken modules fails before anything is installed.

const SUBPROCESS = path self ./subprocess.nu
use $SUBPROCESS [run-command command-failure-message]

# Bump when the generated shim protocol changes (runner <-> shim arguments).
export const COMMAND_SHIM_VERSION = "1"

# Normalized signatures from `scope commands` rows (input/output rows removed).
export def command-signatures [rows: table] {
    $rows | each {|row|
        let params = (
            $row.signatures | values | first
            | where parameter_type not-in ["input" "output"]
            | each {|p| {name: $p.parameter_name kind: $p.parameter_type shape: ($p.syntax_shape | default "") short: ($p.short_flag | default "") optional: $p.is_optional} }
        )
        {name: $row.name description: ($row.description | default "") params: $params}
    } | sort-by name
}

# Hash of command names + parameters only: description edits do not mark the
# installed shim as outdated, signature changes do.
export def command-signatures-hash [sigs: list] {
    $sigs | each {|s| {name: $s.name params: $s.params} } | to nuon | hash sha256
}

def usage-text [sig: record] {
    let parts = ($sig.params | each {|p|
        match $p.kind {
            "switch" => { "[--" + $p.name + "]" }
            "named" => { "[--" + $p.name + " <" + $p.shape + ">]" }
            "positional" => { if $p.optional { "[" + $p.name + "]" } else { "<" + $p.name + ">" } }
            _ => { "..." + $p.name }
        }
    })
    ([$sig.name] | append $parts | str join " ")
}

# Render the installed shim. It must stay dependency-free: no `use` of other
# files, so a broken or moved checkout can never stop Nushell from starting.
export def render-command-shim [sigs: list] {
    let hash = (command-signatures-hash $sigs)
    let header = [
        "# Initial-setup command shim. GENERATED by scripts/refresh-commands.nu; do not edit."
        "# Every command runs from the checkout recorded as tools_root in"
        "# ~/.config/dotfiles/config.nuon (scripts/dotcmd.nu), so checkout updates"
        "# apply immediately. Refresh only when the runner reports an outdated shim."
        ""
        ("const SHIM_VERSION = " + ($COMMAND_SHIM_VERSION | to nuon))
        ("const SIGNATURES_HASH = " + ($hash | to nuon))
        ""
        "def shim-home [] {"
        "    let override = ($env.INITIAL_SETUP_HOME_OVERRIDE? | default \"\" | str trim)"
        "    if ($env.INITIAL_SETUP_TEST_MODE? | default \"\" | str trim) == \"1\" and not ($override | is-empty) { return ($override | path expand) }"
        "    let home_path = ($nu | get --optional home-path)"
        "    if $home_path != null { return $home_path }"
        "    $env.HOME? | default ($env.USERPROFILE? | default \"\")"
        "}"
        ""
        "def shim-run [name: string args: list reload: bool] {"
        "    let config_file = (shim-home | path join \".config\" \"dotfiles\" \"config.nuon\")"
        "    if not ($config_file | path exists) { error make --unspanned {msg: (\"Initial-setup machine config not found: \" + $config_file + \". Run setup first.\")} }"
        "    let tools = (try { open $config_file | get tools_root | into string } catch { \"\" })"
        "    let runner = if ($tools | is-empty) { \"\" } else { $tools | path expand | path join \"scripts\" \"dotcmd.nu\" }"
        "    if ($runner | is-empty) or not ($runner | path exists) {"
        "        error make --unspanned {msg: (\"The Initial-setup checkout (tools_root: \" + $tools + \") has no scripts/dotcmd.nu. Update that checkout, or run scripts/refresh-commands.nu from the checkout you want to use.\")}"
        "    }"
        "    let ok = (try { ^$nu.current-exe --no-config-file $runner $SHIM_VERSION $SIGNATURES_HASH $name ...$args; true } catch { false })"
        "    if not $ok { error make --unspanned {msg: ($name + \" failed.\")} }"
        "    if $reload { exec $nu.current-exe }"
        "}"
    ]
    let defs = ($sigs | each {|sig|
        let has_reload = ($sig.params | any {|p| $p.kind == "switch" and $p.name == "reload" })
        let description = ($sig.description | lines | append "" | append ("Usage: " + (usage-text $sig)) | each {|l| ("# " + $l) | str trim --right })
        let body = if $has_reload {
            "{ shim-run " + ($sig.name | to nuon) + " ($args | where {|a| $a != \"--reload\" }) (\"--reload\" in $args) }"
        } else {
            "{ shim-run " + ($sig.name | to nuon) + " $args false }"
        }
        ([""] | append $description | append ("export def --wrapped " + ($sig.name | to nuon) + " [...args] " + $body) | str join (char nl))
    })
    ($header | append $defs | str join (char nl)) + (char nl)
}

# Signatures of the checkout at tools_root, read by the checkout's own runner
# in a separate process so callers never import the command facade.
export def checkout-command-signatures [tools_root: path] {
    let runner = ($tools_root | path expand | path join "scripts" "dotcmd.nu")
    let result = (run-command $nu.current-exe ["--no-config-file" $runner "__signatures"])
    if not $result.ok {
        error make {msg: (command-failure-message "Read command signatures from the checkout" $result)}
    }
    $result.stdout | from nuon
}

export def generate-command-shim [tools_root: path] {
    render-command-shim (checkout-command-signatures $tools_root)
}
