const CORE_MODULE = path self ./core.nu

use $CORE_MODULE [nu-home]

const GENERATED_INCLUDE = "~/.config/git/initial-setup-identities.gitconfig"
const IDENTITY_INCLUDE_ROOT = "~/.config/git/identities"

export def git-identities-manifest-path [] {
    (nu-home) | path join ".config" "dotfiles" "git-identities.nuon"
}

export def git-identities-generated-path [] {
    (nu-home) | path join ".config" "git" "initial-setup-identities.gitconfig"
}

export def git-identities-dir [] {
    (nu-home) | path join ".config" "git" "identities"
}

export def ensure-git-identities-manifest [] {
    let file = (git-identities-manifest-path)

    if ($file | path exists) {
        return false
    }

    mkdir ($file | path dirname)

    {
        version: 1
        identities: []
    }
    | to nuon
    | save $file

    print ("[create] " + ($file | into string))
    print "[info] Add folder-specific identities with `dotgitids --edit`."
    true
}

export def load-git-identities-manifest [] {
    let file = (git-identities-manifest-path)

    if not ($file | path exists) {
        return {
            version: 1
            identities: []
        }
    }

    let manifest = (open $file)
    let version = ($manifest.version? | default 0)

    if $version != 1 {
        error make {
            msg: ("Unsupported Git identity manifest version: " + ($version | into string))
        }
    }

    let identities = ($manifest.identities? | default [])

    if not (($identities | describe) | str starts-with "list") {
        error make {
            msg: "git-identities.nuon `identities` must be a list."
        }
    }

    for identity in $identities {
        if not (($identity | describe) | str starts-with "record") {
            error make {
                msg: "Each Git identity entry must be a record."
            }
        }

        let enabled = ($identity.enabled? | default true)

        if ($enabled | describe) != "bool" {
            error make {
                msg: "Git identity `enabled` must be a boolean."
            }
        }
    }

    $manifest
}

def validate-text [label: string value: string] {
    if ($value | is-empty) {
        error make { msg: ($label + " must not be empty.") }
    }

    if ($value | str contains (char nl)) or ($value | str contains (char cr)) {
        error make { msg: ($label + " must be a single line.") }
    }
}

def validate-name [name: string] {
    validate-text "Git identity name" $name

    let unsupported = ['/' '\' '"' ':' '*' '?' '<' '>' '|' ' ' (char tab)]

    if ($unsupported | any { |token| ($name | str contains $token) }) {
        error make {
            msg: ("Git identity name contains an unsupported character: " + $name)
        }
    }
}

def normalize-gitdir-pattern [pattern: string] {
    validate-text "Git identity path" $pattern

    if ($pattern | str contains '"') {
        error make {
            msg: ("Git identity path must not contain a double quote: " + $pattern)
        }
    }

    let normalized = ($pattern | path expand | into string | str replace --all '\' '/')

    if ($normalized | str ends-with "/") {
        $normalized
    } else {
        $normalized + "/"
    }
}

def quote-git-value [value: string] {
    let escaped_backslash = ($value | str replace --all '\' '\\')
    let escaped_quote = ($escaped_backslash | str replace --all '"' '\"')
    '"' + $escaped_quote + '"'
}

def identity-file-content [identity: record] {
    let user_name = ($identity.user_name? | default "")
    let email = ($identity.email? | default "")
    let signing_key = ($identity.signing_key? | default "")
    let ssh_key = ($identity.ssh_key? | default "")

    validate-text "Git identity user_name" $user_name
    validate-text "Git identity email" $email

    mut lines = [
        "# Generated by Initial-setup. Edit git-identities.nuon instead."
        "[user]"
        ("    name = " + (quote-git-value $user_name))
        ("    email = " + (quote-git-value $email))
    ]

    if not ($signing_key | is-empty) {
        validate-text "Git identity signing_key" $signing_key
        $lines = ($lines | append ("    signingkey = " + (quote-git-value $signing_key)))
    }

    if not ($ssh_key | is-empty) {
        validate-text "Git identity ssh_key" $ssh_key
        let normalized_key = ($ssh_key | path expand | into string | str replace --all '\' '/')
        let ssh_command = ('ssh -i \"' + $normalized_key + '\" -o IdentitiesOnly=yes')
        $lines = ($lines | append "")
        $lines = ($lines | append "[core]")
        $lines = ($lines | append ("    sshCommand = " + $ssh_command))
    }

    ($lines | append "" | str join (char nl))
}

def validate-identities [identities: list] {
    mut names = []
    mut assigned_paths = []

    for identity in $identities {
        let name = ($identity.name? | default "")
        validate-name $name

        if $name in $names {
            error make {
                msg: ("Duplicate Git identity name: " + $name)
            }
        }

        $names = ($names | append $name)

        let paths = ($identity.paths? | default [])

        if not (($paths | describe) | str starts-with "list") {
            error make {
                msg: ("Git identity '" + $name + "' paths must be a list.")
            }
        }

        if ($paths | is-empty) {
            error make {
                msg: ("Git identity '" + $name + "' must define at least one path.")
            }
        }

        for path_pattern in $paths {
            let normalized_path = (normalize-gitdir-pattern $path_pattern)

            if $normalized_path in $assigned_paths {
                error make {
                    msg: ("Git identity path is assigned more than once: " + $normalized_path)
                }
            }

            $assigned_paths = ($assigned_paths | append $normalized_path)
        }

        identity-file-content $identity | ignore
    }
}

def ensure-global-dispatch-include [] {
    let local = ((nu-home) | path join ".gitconfig.local")

    if not ($local | path exists) {
        [
            "# Machine-local Git overrides."
            "# This file is intentionally not synchronized."
            ""
        ]
        | str join (char nl)
        | save $local
    }

    let content = (open --raw $local)

    if not ($content | str contains "initial-setup-identities.gitconfig") {
        let block = [
            ""
            "# Initial-setup folder-specific Git identities"
            "[include]"
            ("    path = " + $GENERATED_INCLUDE)
            ""
        ] | str join (char nl)

        ($content + $block) | save --force $local
        print "[update] Git identity dispatcher include enabled"
    }
}

export def active-git-identities [] {
    let manifest = (load-git-identities-manifest)

    $manifest.identities
    | where { |identity| $identity.enabled? | default true }
}

export def apply-git-identities [] {
    if (which git | is-empty) {
        print "[skip] git is not installed"
        return 0
    }

    ensure-git-identities-manifest | ignore
    let identities = (active-git-identities)
    validate-identities $identities

    let identities_dir = (git-identities-dir)
    let dispatcher = (git-identities-generated-path)

    mkdir $identities_dir
    mkdir ($dispatcher | path dirname)

    mut dispatch_lines = [
        "# Generated by Initial-setup. Edit ~/.config/dotfiles/git-identities.nuon instead."
        ""
    ]
    mut expected_files = []

    for identity in $identities {
        let name = ($identity.name? | default "")
        let paths = ($identity.paths? | default [])
        let identity_file = ($identities_dir | path join ($name + ".gitconfig"))
        identity-file-content $identity | save --force $identity_file
        $expected_files = ($expected_files | append ($identity_file | path basename))

        for path_pattern in $paths {
            let pattern = (normalize-gitdir-pattern $path_pattern)
            $dispatch_lines = ($dispatch_lines | append ('[includeIf "gitdir/i:' + $pattern + '"]'))
            $dispatch_lines = ($dispatch_lines | append ("    path = " + $IDENTITY_INCLUDE_ROOT + "/" + $name + ".gitconfig"))
            $dispatch_lines = ($dispatch_lines | append "")
        }
    }

    $dispatch_lines | str join (char nl) | save --force $dispatcher

    for item in (ls $identities_dir | where type == file) {
        let basename = ($item.name | path basename)

        if ($basename | str ends-with ".gitconfig") and not ($basename in $expected_files) {
            rm $item.name
            print ("[remove] stale Git identity file: " + $basename)
        }
    }

    ensure-global-dispatch-include

    print ("[ok] Git folder identities applied: " + (($identities | length) | into string))
    $identities | length
}

export def check-git-identities [] {
    let manifest_file = (git-identities-manifest-path)

    if not ($manifest_file | path exists) {
        print ("[--] Git identity manifest not configured: " + ($manifest_file | into string))
        return
    }

    let identities = (active-git-identities)
    validate-identities $identities

    print ("Manifest     : " + ($manifest_file | into string))
    print ("Identities   : " + (($identities | length) | into string))

    if ($identities | is-empty) {
        print "[--] No folder-specific Git identities configured"
        return
    }

    for identity in $identities {
        let name = ($identity.name? | default "")
        let paths = ($identity.paths? | default [])
        let email = ($identity.email? | default "")
        let ssh_key = ($identity.ssh_key? | default "")

        print ("[ok] " + $name + " -> " + ($paths | str join ", ") + " -> " + $email)

        if not ($ssh_key | is-empty) {
            let expanded_key = ($ssh_key | path expand)

            if ($expanded_key | path exists) {
                print ("     SSH key: " + ($expanded_key | into string))
            } else {
                print ("[WARN] SSH key missing for " + $name + ": " + ($expanded_key | into string))
            }
        }
    }
}
